[project]
name = "aptima_analysis"
version = "0.1.0"
description = "EEG analysis pipeline for the APTIMA project."

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

